### ISSUE TITLE
Error: Class 'WebPify\WebPify' not found 

### ISSUE THREAD

**Issue by Blacklotis2** [Chrico/webpify#2]
Can't seem to make this work. Getting this after activating the plugin.

#0 /home/215554.cloudwaysapps.com/npchbqsvwv/public_html/wp-includes/class-wp-hook.php(286): WebPify\initialize('')
#1 /home/215554.cloudwaysapps.com/npchbqsvwv/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /home/215554.cloudwaysapps.com/npchbqsvwv/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home/215554.cloudwaysapps.com/npchbqsvwv/public_html/wp-settings.php(327): do_action('plugins_loaded')
#4 /home/215554.cloudwaysapps.com/npchbqsvwv/public_html/wp-config.php(74): require_once('/home/215554.cl...')
#5 /home/215554.cloudwaysapps.com/npchbqsvwv/public_html/wp-load.php(37): require_once('/home/215554.cl...')
#6 /home/215554.cloudwaysapps.com/npchbqsvwv/public_html/wp-admin/admin.php(31): require_once('/home/215554.cl...')
#7 /home/215554.cloudwaysapps.com/npchbqsvwv/public_html/wp-admin/options-general.php(10): require_once('/home/215554.cl...')
#8 {main}

**Comment by Chrico** [comment]
Howdy.

This Plugin is only usable in a composer enviornment. Have you installed it via composer or just downloaded/checked out? :)
